[package]
name = "riker_bench"
version = "0.1.0"
authors = ["hardliner66 <hardliner66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riker = { git = "https://github.com/hardliner66/riker" }
#riker = { git = "https://github.com/hardliner66/riker", branch = "remove_need_for_manual_boxing" }
#riker = { git = "https://github.com/hardliner66/riker", branch = "actor_creation" }